name: Deploy

on:
  workflow_run:
    workflows: ["Java CI with Gradle"] 
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          aws-region: us-east-1

      - name: Deploy to AWS
        run: |
            aws deploy create-deployment \
              --application-name ApiDeploy \
              --deployment-group-name GrupoDeploy \
              --github-location repository=${{github.repository}},commitId=${{github.sha}} \
              --description "Deployed from GitHub"
              aws cloudformation deploy --profile default --stack-name PilaDeploy --template-file ubuntu.yml
